steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/my-project/my-repo:$COMMIT_SHA'
      - .
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/my-project/my-repo:$COMMIT_SHA'
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - deploy
      - 'my-service'
      - '--image'
      - 'gcr.io/my-project/my-repo:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
    entrypoint: gcloud
    id: Deploy

timeout: 1200s
images:
  - 'gcr.io/my-project/my-repo:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
