version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=FinancialTransactionDb;User=sa;Password=YourStrong!Passw0rd;
    networks:
      - financialtransactionapi-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - financialtransactionapi-sqldata:/var/opt/mssql
    networks:
      - financialtransactionapi-network

networks:
  financialtransactionapi-network:
    driver: bridge

volumes:
  financialtransactionapi-sqldata:
    driver: local